server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import:
#      - optional:classpath:/nacos-common.yml
      - nacos:db-common.yml?refresh=true
      - nacos:common.yml?refresh=true
      - nacos:${spring.application.name}.yml?refresh=true



  cloud:
    nacos:
      server-addr: 192.168.10.210:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.10.210:8848
        namespace: luckyh-cloud
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.10.210:8848
        namespace: luckyh-cloud
        group: DEFAULT_GROUP

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.luckyh.cloud.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG

